/**
 * Tests for Story 1.5.6 — Skill auto-templating
 *
 * Covers:
 *   1. buildStubMarkdown fills the template correctly from a fixture candidate
 *   2. CANDIDATE banner is always the first non-empty line
 *   3. AI failure does NOT break stub generation (best-effort)
 *   4. POST /skills/:id/stub returns correct shape + writes file
 *   5. GET /skills/stubs lists generated stubs
 *   6. Auto-install to ~/.claude/skills/ is NOT attempted
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { createRequire } from 'module';
import request from 'supertest';
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { buildStubMarkdown, generateStub } from '../src/skills/stub-generator.js';

const require = createRequire(import.meta.url);

// ── Fixture ───────────────────────────────────────────────────────────────────

const FIXTURE_CANDIDATE = {
  id: 1,
  signature: 'abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
  name: null,
  description: null,
  tool_sequence_json: JSON.stringify(['Read', 'Edit', 'Bash']),
  frequency: 7,
  example_session_ids_json: JSON.stringify(['s1', 's2', 's3', 's4']),
  first_seen: Date.now() - 100_000,
  last_seen: Date.now(),
  promoted_at: null,
};

// ── Unit: buildStubMarkdown ───────────────────────────────────────────────────

describe('buildStubMarkdown', () => {
  it('starts with the CANDIDATE HTML comment banner', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    const lines = md.split('\n');
    // First non-empty line must be the CANDIDATE comment
    const firstNonEmpty = lines.find((l) => l.trim().length > 0);
    expect(firstNonEmpty).toMatch(/CANDIDATE/);
    expect(firstNonEmpty).toContain('generated by claude-fuse');
  });

  it('includes the n-gram tool sequence in a comment line', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('Read → Edit → Bash');
    expect(md).toContain('×7');
  });

  it('includes frequency + session counts', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('Frequency: 7');
    expect(md).toContain('Sessions: 4');
  });

  it('generates one step bullet per tool', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('1. Read:');
    expect(md).toContain('2. Edit:');
    expect(md).toContain('3. Bash:');
  });

  it('has ## Trigger, ## Steps, ## Notes sections', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('## Trigger');
    expect(md).toContain('## Steps');
    expect(md).toContain('## Notes');
  });

  it('includes # Skill: heading with tool sequence', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('# Skill: Read → Edit → Bash');
  });

  it('includes CTA to promote to Brain', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).toContain('brain memory_save skill:');
  });

  it('does NOT mention ~/.claude/skills/ auto-install', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE);
    expect(md).not.toContain('~/.claude/skills');
    expect(md).not.toContain('auto-install');
  });
});

describe('buildStubMarkdown with AI result', () => {
  it('injects AI trigger labelled [AI — candidate suggestion]', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE, {
      trigger: 'When developer searches then edits a file',
      notes: 'Typical code-edit flow',
    });
    expect(md).toContain('When developer searches then edits a file');
    expect(md).toContain('[AI — candidate suggestion]');
  });

  it('falls back gracefully when aiResult is null', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE, null);
    expect(md).toContain('not generated');
    expect(md).toContain('## Trigger');
  });

  it('AI failure does NOT remove CANDIDATE banner', () => {
    const md = buildStubMarkdown(FIXTURE_CANDIDATE, null);
    const lines = md.split('\n');
    const firstNonEmpty = lines.find((l) => l.trim().length > 0);
    expect(firstNonEmpty).toMatch(/CANDIDATE/);
  });
});

// ── Unit: generateStub (file write) ──────────────────────────────────────────

describe('generateStub file write', () => {
  let tmpDir;

  beforeAll(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'fuse-stubs-test-'));
    process.env.CLAUDE_FUSE_DATA_DIR = tmpDir;
  });

  afterAll(() => {
    delete process.env.CLAUDE_FUSE_DATA_DIR;
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('writes a .md file and returns path + markdown', () => {
    const result = generateStub(FIXTURE_CANDIDATE);
    expect(result.path).toMatch(/\.md$/);
    expect(existsSync(result.path)).toBe(true);
    const content = readFileSync(result.path, 'utf8');
    expect(content).toContain('CANDIDATE');
    expect(content).toContain('Read → Edit → Bash');
  });

  it('filename contains the sig prefix and a date', () => {
    const result = generateStub(FIXTURE_CANDIDATE);
    expect(result.filename).toMatch(/^abcdef123456-\d{8}\.md$/);
  });

  it('CANDIDATE banner is the first non-whitespace line in the file', () => {
    const result = generateStub(FIXTURE_CANDIDATE);
    const lines = readFileSync(result.path, 'utf8').split('\n');
    const first = lines.find((l) => l.trim().length > 0);
    expect(first).toMatch(/CANDIDATE/);
  });
});

// ── Integration: POST /skills/:id/stub and GET /skills/stubs ─────────────────

let tmpDir2;
let app;
let db;

beforeAll(async () => {
  tmpDir2 = mkdtempSync(join(tmpdir(), 'fuse-stubs-api-test-'));

  process.env.CLAUDE_FUSE_DB = join(tmpDir2, 'test.db');
  process.env.CLAUDE_FUSE_DATA_DIR = tmpDir2;
  process.env.CLAUDE_FUSE_NO_LISTEN = '1';
  process.env.CLAUDE_FUSE_LEDGER_PATH = join(tmpDir2, 'MISTAKES_LEDGER.md');
  // Ensure AI key is NOT set — tests run without AI
  delete process.env.CLAUDE_FUSE_AI_API_KEY;

  const { writeFileSync } = await import('fs');
  writeFileSync(process.env.CLAUDE_FUSE_LEDGER_PATH, '## M1 — seed\n\ncontent.\n', 'utf8');

  await import('../src/migrations/run.js');

  const { default: appModule } = await import('../src/server.js');
  app = appModule;

  const { getDb } = await import('../src/db.js');
  db = getDb();

  // Seed a skill candidate
  db.prepare(`
    INSERT INTO skill_candidates
      (signature, tool_sequence_json, frequency, example_session_ids_json, first_seen, last_seen)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run(
    'abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
    JSON.stringify(['Read', 'Edit', 'Bash']),
    7,
    JSON.stringify(['s1', 's2', 's3']),
    Date.now() - 50000,
    Date.now(),
  );
});

afterAll(() => {
  rmSync(tmpDir2, { recursive: true, force: true });
});

describe('POST /skills/:id/stub', () => {
  it('returns 200 with success + path + markdown', async () => {
    const res = await request(app).post('/skills/1/stub');
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.path).toMatch(/\.md$/);
    expect(typeof res.body.markdown).toBe('string');
    expect(res.body.markdown).toContain('CANDIDATE');
    expect(res.body.ai_used).toBe(false);
  });

  it('stub file exists on disk', async () => {
    const res = await request(app).post('/skills/1/stub');
    expect(existsSync(res.body.path)).toBe(true);
  });

  it('returns 404 for unknown id', async () => {
    const res = await request(app).post('/skills/9999/stub');
    expect(res.status).toBe(404);
  });

  it('CANDIDATE banner is first non-empty line in returned markdown', async () => {
    const res = await request(app).post('/skills/1/stub');
    const lines = res.body.markdown.split('\n');
    const first = lines.find((l) => l.trim().length > 0);
    expect(first).toMatch(/CANDIDATE/);
  });

  it('does NOT include ai_used=true when CLAUDE_FUSE_AI_API_KEY absent', async () => {
    const res = await request(app).post('/skills/1/stub?ai=true');
    expect(res.status).toBe(200);
    expect(res.body.ai_used).toBe(false);
  });
});

describe('GET /skills/stubs', () => {
  it('returns 200 with stubs array', async () => {
    // Generate a stub first so the dir exists
    await request(app).post('/skills/1/stub');

    const res = await request(app).get('/skills/stubs');
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body.stubs)).toBe(true);
    expect(typeof res.body.count).toBe('number');
  });

  it('each stub entry has required fields', async () => {
    await request(app).post('/skills/1/stub');

    const res = await request(app).get('/skills/stubs');
    for (const stub of res.body.stubs) {
      expect(stub).toHaveProperty('filename');
      expect(stub).toHaveProperty('path');
      expect(stub).toHaveProperty('size_bytes');
      expect(stub).toHaveProperty('created_at');
      expect(stub.filename).toMatch(/\.md$/);
    }
  });
});
